#!/usr/local/bin/perl

if ( $ARGV[0] eq "") {
  print "Usage: rsimon [time in mins]\n";
  exit ();
}

if ($fork = fork()){
  exit
}
else{

  $time = $ARGV[0] * 60;
  sleep $time;

  while (1){
    system "/usr/local/bin/xmessage -fg black -bg white -file /nfs/team71/worm/krb/bin/rsimon.msg -buttons \"Ok\":0,\"EXIT\":1 -center";

    if ( $? eq 0 ){
      sleep $time;
    }
    else{     
      exit();
    }

  }

}
